steps:
  # - name: node:12-slim
  #   entrypoint: npm
  #   args: ['install']
  # - name: node:12-slim
  #   entrypoint: npm
  #   args: ['test', '--', '--watchAll=false']
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--build-arg",
        "REACT_APP_ENV=${_SDLC}",
        "-t",
        "eu.gcr.io/${PROJECT_ID}/${_CONTAINER_NAME}",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "eu.gcr.io/${PROJECT_ID}/${_CONTAINER_NAME}"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "${_SERVICE_NAME}",
        "--image",
        "eu.gcr.io/${PROJECT_ID}/${_CONTAINER_NAME}",
        "--region",
        "${_REGION}",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]
images:
  - "eu.gcr.io/${PROJECT_ID}/${_CONTAINER_NAME}"
timeout: 15m
